
const EMPLOYEES_REQUESTED = 'all/EMPLOYEES_REQUESTED';
const EMPLOYEES_RECEIVED = 'all/EMPLOYESS_RECEIVED';
const EMPLOYEES_ERROR = 'all/EMPLOYEES_ERROR';
const CSV_UPLOAD_REQUESTED = 'one/CSV_UPLOAD_REQUESTED';
const CSV_UPLOAD_RECEIVED = 'one/CSV_UPLOAD_RECEIVED';
const CSV_UPLOAD_ERROR = 'one/CSV_UPLOAD_ERROR';


const Actions = {
  EMPLOYEES_REQUESTED,
  EMPLOYEES_RECEIVED,
  EMPLOYEES_ERROR,
  CSV_UPLOAD_REQUESTED,
  CSV_UPLOAD_RECEIVED,
  CSV_UPLOAD_ERROR
};

export default Actions;

